import Head from "next/head";
import { React, Component } from "../libraries";
import AppLayout from "../components/templates/AppLayout";

export default function About() {
  return (
    <div>
      <Head>
        <title>About :: Atomic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppLayout
        mode={"dev"}
        title="About"
        description="description About page"
        showSidebar={true}
        showHeader={true}
        showFooter={true}
      >
        <div>about</div>
      </AppLayout>
    </div>
  );
}
